version:  "3"

services:
  scrapper:
    container_name: scrapper
    build: .
    env_file:
      - .env
    volumes:
      - ./:/usr/src/glovo
    entrypoint: ["sh", "/usr/src/glovo/entrypoint.sh"]
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  #MySQL Service
  mysql:
    image: mysql:8.0.17
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    user: root

volumes:
  dbdata:
