version:  "3"

services:
  scrapper:
    container_name: scrapper
    build: .
    env_file:
      - .env
    volumes:
      - ./:/usr/src/glovo
    entrypoint: ["sh", "/usr/src/glovo/entrypoint.sh"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

